// convex/_generated/dataModel.d.ts
// Type stubs — full model generated by `npx convex dev`

export type Id<T extends string> = string & { __table: T };
export type Doc<T extends string> = Record<string, any>;
export declare const Doc: any;
