// convex/_generated/server.d.ts
// Type stubs for Convex server functions — generated by `npx convex dev`
// These are minimal stubs to satisfy TypeScript. Full types are generated at build time.

export type QueryCtx = {
  db: DatabaseReader;
  auth: { getUserIdentity: () => Promise<{ subject: string; email?: string } | null> };
};

export type MutationCtx = {
  db: DatabaseWriter;
  auth: { getUserIdentity: () => Promise<{ subject: string; email?: string } | null> };
};

export type ActionCtx = {
  auth: { getUserIdentity: () => Promise<{ subject: string; email?: string } | null> };
  runQuery: (query: any, args?: any) => Promise<any>;
  runMutation: (mutation: any, args?: any) => Promise<any>;
};

export type DatabaseReader = any;
export type DatabaseWriter = any;

export function query(fn: { args: any; handler: (ctx: QueryCtx, args: any) => Promise<any> }): any {
  return fn;
}

export function mutation(fn: { args: any; handler: (ctx: MutationCtx, args: any) => Promise<any> }): any {
  return fn;
}

export function internalMutation(fn: { args: any; handler: (ctx: MutationCtx, args: any) => Promise<any> }): any {
  return fn;
}

export function internalQuery(fn: { args: any; handler: (ctx: QueryCtx, args: any) => Promise<any> }): any {
  return fn;
}

export function action(fn: { args: any; handler: (ctx: ActionCtx, args: any) => Promise<any> }): any {
  return fn;
}

export function internalAction(fn: { args: any; handler: (ctx: ActionCtx, args: any) => Promise<any> }): any {
  return fn;
}
